### ISSUE TITLE
Goland 2021.3插件不起作用

### ISSUE THREAD

**Issue by maliyan** [TarsCloud/TarsTools#6]
把所有插件都禁用了，还是不会语法高亮，看样子像是插件没起作用；禁用->重启->重新启用->重启，也不行，辛苦帮忙看看最新版的Goland安装这个插件有啥问题没？
没头绪要从哪里定位问题了

**Comment by kyy1996** [comment]
请按如下步骤检查是否之前手动设置了*jce/tars*文件的类型：
1. 打开Preference设置，选择*Editor*->*File Types*->*Recognizd File Types*->*Text*，检查右边*FIle name patterns*窗格中有没有`*.jce`或`*.ars`，有的话请移除。
![image](https://user-images.githubusercontent.com/13816556/145667221-8ba18e39-7268-458b-a211-1db453d1f37b.png)
2. 右键*jce/tars*文件，看看有没有*Revert FIle Tpe Override*选项，有的话点击它。
![image](https://user-images.githubusercontent.com/13816556/145667196-71f4cc23-e7c5-47a1-a89a-3830e34e7377.png)

**Comment by maliyan** [comment]
Nice!!!搞定，多谢~~~
